package demo;

import demo.cli.CommandLineArguments;
import demo.domain.Document;

import java.io.IOException;
import java.io.PrintWriter;
import java.io.UncheckedIOException;
import java.nio.file.Files;
import java.nio.file.Path;

public final class Main {

    public static void main(final String[] args) {
        final CommandLineArguments cla = CommandLineArguments.parse(args);

        if (cla.showHelp()) {
            cla.printHelp();
            return;
        }

        final Path path = cla.playbook().toAbsolutePath();
        System.out.println("Running file: " + path);

        final Document document = Document.parse(path);

        /* TODO: create the parent directories if missing */
        final Path output = cla.output().toAbsolutePath();

        try (PrintWriter writer = new PrintWriter(Files.newBufferedWriter(output))) {
            writer.println("[//]: # (Automatically generated by Sociable Weaver)");

            document.run(o -> {
                writer.println(o);
                writer.flush();
            });
        } catch (final IOException e) {
            throw new UncheckedIOException("Failed to write output", e);
        }
    }
}
