#![warn(missing_debug_implementations, rust_2018_idioms)]

use std::error::Error;
use std::fmt::{Debug, Display};
use std::fs::OpenOptions;
use std::io;
use std::io::{ErrorKind, Write};

use colored::Colorize;

use crate::domain::Entry::Heading;
use crate::domain::MarkdownRunnable;
use crate::domain::{Context, Document};
use crate::utils::cla::Args;

mod domain;
mod utils;

fn main() -> io::Result<()> {
    let args = Args::create();

    for file in args.files() {
        println!("Running file: {}", file);
        let json = file.read();
        let document = Document::parse(&json).expect("Failed to parse JSON file");
        let mut context = Context::from(&document).with_current_dir(file.parent_dir());

        create_file(
            "README.md",
            "[//]: # (Automatically generated by Sociable Weaver)",
        )
        .expect("Failed to create MARKDOWN file");

        for entry in document.entries() {
            match entry {
                Heading(heading) => append_to_file("README.md", heading.to_markdown())?,
                // Command(command) => {
                //     if Executor::execute(command, &mut context).is_err() {
                //         return ExitCode::FAILURE;
                //     }
                // }
                // Breakpoint(breakpoint) => {
                //     /* TODO: make better use of 'polymorphism' */
                //     println!("{}", "Press enter to continue".cyan());
                //     if let Some(comment) = breakpoint.comment() {
                //         println!("{}", comment.cyan());
                //     }
                //     let mut input = String::new();
                //     if io::stdin().read_line(&mut input).is_err() {
                //         return ExitCode::FAILURE;
                //     }
                // }
                _ => { /* Skip for now */ }
            }
        }
    }

    Ok(())
}

fn create_file(path: &str, text: &str) -> io::Result<()> {
    let mut file = OpenOptions::new()
        .write(true)
        .truncate(true)
        .create(true)
        .open(path)?;

    writeln!(file, "{}", text)
}

fn append_to_file(path: &str, result: Result<String, String>) -> io::Result<()> {
    let mut file = OpenOptions::new().write(true).append(true).open(path)?;

    match result {
        Ok(text) => writeln!(file, "{}", text),
        Err(error) => {
            writeln!(file, "{}", error)?;
            Err(io::Error::new(ErrorKind::Other, error))
        }
    }
}
